version: '3.4'

services:
  devcontainer:
    container_name: my-solution
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "19001:19001"
    command: sleep infinity
